name: Build and Deploy to GitHub Pages

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Add wasm32
        run: rustup target add wasm32-unknown-unknown

      - name: Install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli

      - name: Build the project
        run: |
          cargo build --release --target wasm32-unknown-unknown
          wasm-bindgen --no-typescript --target web --out-dir ./out/ --out-name "unnamed_game" ./target/wasm32-unknown-unknown/release/unnamed_game.wasm

      - name: Setup Pages Directory
        run: |
          cp index.html ./out
          cp -r assets ./out

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
